# Generated by Django 5.2.7 on 2026-09-11 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('transfer', 'Перемещение'), ('adjust', 'Корректировка'), ('produce_in', 'Изготовление (приход)'), ('produce_out', 'Изготовление (расход)'), ('scrap', 'Списание в брак')], max_length=16, verbose_name='Тип движения'),
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_source_used', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Израсходовано заготовок')),
                ('qty_good', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Изготовлено годных')),
                ('qty_scrap', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Брак (расчётный)')),
                ('qty_reserve', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Оставлено в задел')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('scrap_written_off', models.BooleanField(default=False, help_text='Отмечается, когда оператор подписал недельный акт списания', verbose_name='Брак списан актом')),
                ('scrap_written_off_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата списания брака')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_result', to='inventory.product', verbose_name='Деталь (результат)')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_source', to='inventory.product', verbose_name='Литьё (источник)')),
            ],
            options={
                'verbose_name': 'Производственная операция',
                'verbose_name_plural': 'Производственные операции',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouse.productionrun', verbose_name='Производственная операция'),
        ),
    ]
