# Generated by Django 5.2.7 on 2026-09-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_movement_movement_type_productionrun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Кто фактически выполнил операцию. Может отличаться от автора записи.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs_as_operator', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='scrap_reason',
            field=models.CharField(blank=True, default='', help_text='Заполняется, если брак > 0', max_length=255, verbose_name='Причина брака'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='qty_scrap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Брак'),
        ),
    ]
