# Generated by Django 5.2.7 on 2026-09-11 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_productionrun_operator_productionrun_scrap_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrun',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs_as_operator', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='qty_scrap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Брак (всего)'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='scrap_reason',
            field=models.CharField(blank=True, default='', help_text='Устаревшее поле. Используйте ScrapEntry для детализации.', max_length=255, verbose_name='Причина брака (legacy)'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='scrap_written_off',
            field=models.BooleanField(default=False, verbose_name='Брак списан актом'),
        ),
        migrations.CreateModel(
            name='ScrapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина брака')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество, шт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_entries', to='warehouse.productionrun', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Причина брака',
                'verbose_name_plural': 'Причины брака',
                'ordering': ('-quantity',),
            },
        ),
    ]
