# Generated by Django 5.2.7 on 2026-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_productionrun_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='qty_from_reserve',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Сколько готовых деталей взято из свободного остатка (задела)', max_digits=14, verbose_name='Взято из задела'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='scrap_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Причина брака (legacy)'),
        ),
    ]
