# Generated by Django 5.2.7 on 2026-09-14 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
("warehouse", "0005_productionrun_qty_from_reserve_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='inventory.product', verbose_name='Главный артикул (кэш первой строки)'),
        ),
        migrations.AlterField(
            model_name='container',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Общее количество (сумма строк)'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='qty_from_reserve',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Взято из задела'),
        ),
        migrations.CreateModel(
            name='ContainerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.container', verbose_name='Тара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='container_lines', to='inventory.product', verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Содержимое тары',
                'verbose_name_plural': 'Содержимое тары',
                'ordering': ('-quantity',),
                'unique_together': {('container', 'product')},
            },
        ),
    ]
