# Generated by Django 5.2.7 on 2026-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_data_create_reserve_wh'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, help_text='Когда в последний раз печатали этикетку Code128', null=True, verbose_name='Этикетка напечатана'),
        ),
    ]
