# Generated by Django 5.2.7 on 2026-09-15 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_container_label_printed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('seq', models.PositiveIntegerField(verbose_name='Порядковый номер за год')),
                ('note_date', models.DateField(verbose_name='Дата накладной')),
                ('from_name', models.CharField(default='', max_length=255, verbose_name='Отправитель')),
                ('from_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес отправителя')),
                ('to_name', models.CharField(default='', max_length=255, verbose_name='Получатель')),
                ('to_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес получателя')),
                ('total_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Всего шт')),
                ('total_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Всего вес, кг')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Накладная на отгрузку',
                'verbose_name_plural': 'Накладные на отгрузку',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShipmentNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код тары')),
                ('product_article', models.CharField(max_length=64, verbose_name='Артикул')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('uom', models.CharField(default='шт', max_length=16, verbose_name='Ед.')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кол-во')),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Вес, кг')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_lines', to='warehouse.container', verbose_name='Тара')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.shipmentnote', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Строка накладной',
                'verbose_name_plural': 'Строки накладных',
                'ordering': ('sequence', 'id'),
            },
        ),
    ]
