# Generated by Django 5.2.7 on 2026-09-15 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_mo5_product_mo6_product_mo7_product_mo8'),
        ('warehouse', '0010_shipmentnote_shipmentnoteline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_runs_finished', to=settings.AUTH_USER_MODEL, verbose_name='Завершил'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='completed', help_text='Для новых партий всегда in_progress (ставится автоматически)', max_length=16, verbose_name='Статус партии'),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('warehouse', 'На складке (заготовка)'), ('in_production', 'В работе (литАрт → мехАрт)'), ('waiting_milling', 'Ждёт фрезеровки'), ('waiting_packing', 'Ждёт упаковки'), ('ready_to_ship', 'Готов к отгрузке'), ('shipped', 'Отгружена'), ('empty', 'Пустая (болванка)'), ('written_off', 'Списана')], default='warehouse', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='containerevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Создана'), ('issued', 'Выдана в производство'), ('returned', 'Возвращена из производства'), ('moved', 'Перемещена'), ('shipped', 'Отгружена'), ('adjusted', 'Скорректирована'), ('status_changed', 'Смена статуса')], max_length=16, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Старт (выдача в работу)'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs_result', to='inventory.product', verbose_name='Деталь (результат)'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='qty_good',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Изготовлено годных'),
        ),
    ]
