# Generated by Django 5.2.7 on 2026-09-15 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_mo5_product_mo6_product_mo7_product_mo8'),
        ('warehouse', '0011_productionrun_finished_at_productionrun_finished_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='qty_returned',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Возвращено в исходные тары'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs_result', to='inventory.product', verbose_name='Главный результат (кэш первого)'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='qty_good',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Годных (кэш суммы результатов)'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='qty_scrap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Брак (кэш суммы результатов)'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='qty_source_used',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Взято заготовок'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='completed', max_length=16, verbose_name='Статус партии'),
        ),
        migrations.CreateModel(
            name='ProductionRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_good', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Годных')),
                ('qty_scrap', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Брак (кэш суммы причин)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_results_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_results', to='inventory.product', verbose_name='Деталь')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='warehouse.productionrun', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Результат партии',
                'verbose_name_plural': 'Результаты партии',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='scrapentry',
            name='production_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrap_entries', to='warehouse.productionrunresult', verbose_name='Результат партии (для новых)'),
        ),
    ]
