# Generated by Django 5.2.7 on 2026-09-16 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_mo5_product_mo6_product_mo7_product_mo8'),
        ('orders', '0002_orderline_machine_orderline_places_and_more'),
        ('warehouse', '0012_productionrun_qty_returned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('turning', 'Токарка'), ('milling', 'Фрезеровка'), ('packing', 'Упаковка'), ('move', 'Перемещение'), ('ship', 'Отгрузка'), ('other', 'Прочее')], db_index=True, default='other', max_length=16, verbose_name='Тип операции')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OperationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('from', 'Взято'), ('to', 'Положено'), ('scrap', 'Брак')], db_index=True, max_length=8, verbose_name='Направление')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('scrap_reason', models.CharField(blank=True, choices=[('setup', 'Наладка'), ('foundry', 'Литейный брак'), ('production', 'Производственный брак'), ('negligence', 'Халатность')], default='', max_length=16, verbose_name='Причина брака')),
            ],
            options={
                'verbose_name': 'Строка операции',
                'verbose_name_plural': 'Строки операции',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='productionrun',
            options={'ordering': ('-created_at',), 'verbose_name': 'Производственная операция (legacy)', 'verbose_name_plural': 'Производственные операции (legacy)'},
        ),
        migrations.AlterModelOptions(
            name='productionrunresult',
            options={'ordering': ('created_at',), 'verbose_name': 'Результат партии (legacy)', 'verbose_name_plural': 'Результаты партии (legacy)'},
        ),
        migrations.AlterModelOptions(
            name='scrapentry',
            options={'ordering': ('-quantity',), 'verbose_name': 'Причина брака (legacy)', 'verbose_name_plural': 'Причины брака (legacy)'},
        ),
        migrations.AddField(
            model_name='container',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Свободный текст: «токарка», «на упаковку», «задел» и т.п.', max_length=64, verbose_name='Метка'),
        ),
        migrations.AddField(
            model_name='container',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='Если заполнено — тара ушла со склада, в списках не показывается', null=True, verbose_name='Отгружена'),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('warehouse', 'На складке (заготовка)'), ('in_production', 'В работе (литАрт → мехАрт)'), ('waiting_milling', 'Ждёт фрезеровки'), ('waiting_packing', 'Ждёт упаковки'), ('ready_to_ship', 'Готов к отгрузке'), ('shipped', 'Отгружена'), ('empty', 'Пустая (болванка)'), ('written_off', 'Списана')], default='warehouse', max_length=16, verbose_name='Статус (legacy)'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouse.productionrun', verbose_name='Производственная операция (legacy)'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['shipped_at'], name='warehouse_c_shipped_98b232_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['label'], name='warehouse_c_label_b6527b_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['warehouse', 'shipped_at'], name='warehouse_c_warehou_1a398b_idx'),
        ),
        migrations.AddField(
            model_name='operation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='operation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='operationline',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_lines', to='warehouse.container', verbose_name='Тара'),
        ),
        migrations.AddField(
            model_name='operationline',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouse.operation', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='operationline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_lines', to='inventory.product', verbose_name='Артикул'),
        ),
        migrations.AddIndex(
            model_name='operationline',
            index=models.Index(fields=['direction'], name='warehouse_o_directi_495a30_idx'),
        ),
        migrations.AddIndex(
            model_name='operationline',
            index=models.Index(fields=['container', 'direction'], name='warehouse_o_contain_afe30e_idx'),
        ),
    ]
