# Generated by Django 5.2.7 on 2026-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_operation_operationline_alter_productionrun_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='packed_at',
            field=models.DateTimeField(blank=True, help_text='Когда упаковали. Пусто — ещё не готова к отгрузке.', null=True, verbose_name='Упакована'),
        ),
    ]
