# Generated by Django 5.2.7 on 2026-09-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_note', models.CharField(default='СОБСТВЕННОСТЬ ООО «Ромашка»', max_length=255, verbose_name='Строка собственности')),
                ('packing_list_title', models.CharField(default='УПАКОВОЧНЫЙ ЛИСТ', max_length=128, verbose_name='Заголовок документа')),
                ('customer_name', models.CharField(default='ООО «Ромашка»', max_length=255, verbose_name='Наименование заказчика')),
                ('customer_address', models.TextField(default='000000, г. Город, ул. Примерная, д. 1, офис 1.\nСклад: 000000, РФ, обл. Примерная, р-н Примерный, пос. Примерный, промплощадка №1, д. 1', verbose_name='Адрес заказчика')),
                ('supplier_name', models.CharField(default='ООО «Пример»', max_length=255, verbose_name='Наименование поставщика')),
                ('supplier_address', models.TextField(default='г. Город, Производственный проезд, 1.', verbose_name='Адрес поставщика')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Реквизиты компании',
                'verbose_name_plural': 'Реквизиты компании',
            },
        ),
    ]
