# Generated by Django 5.2.7 on 2026-09-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='foundry_customer_address',
            field=models.TextField(default='Республика Примерная, город Примерный, Производственный проезд, 1', verbose_name='Адрес заказчика (литейка)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='foundry_customer_name',
            field=models.CharField(default='ООО «Пример»', max_length=255, verbose_name='Заказчик (литейка)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='foundry_ownership_note',
            field=models.CharField(default='СОБСТВЕННОСТЬ ООО «ПРИМЕР»', max_length=255, verbose_name='Строка собственности (литейка)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='foundry_supplier_address',
            field=models.TextField(default='Республика Примерная, Примерный район, поселок Примерный, ул. Полевая 1', verbose_name='Адрес поставщика (литейка)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='foundry_supplier_name',
            field=models.CharField(default='ООО «Завод»', max_length=255, verbose_name='Поставщик (литейка)'),
        ),
    ]
