# Generated by Django 5.2.7 on 2026-09-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('foundry', 'Литейка'), ('admin', 'Администратор')], default='user', max_length=16, verbose_name='Роль'),
        ),
    ]
