# Generated by Django 5.2.7 on 2026-09-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=16, verbose_name='Версия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
                'ordering': ('product', '-is_active', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(blank=True, default='', max_length=32, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('product_type', models.CharField(choices=[('raw', 'Сырьё'), ('casting', 'Заготовка / литьё'), ('part', 'Деталь'), ('finished', 'Готовая продукция')], max_length=16, verbose_name='Тип')),
                ('uom', models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг')], default='pcs', max_length=8, verbose_name='Ед. изм.')),
                ('weight_g', models.DecimalField(decimal_places=3, default=0, help_text='Вес одной штуки в граммах (например, 2186 для 2.186 кг)', max_digits=12, verbose_name='Вес единицы, г')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Мин. остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Категория')),
                ('mo1', models.ForeignKey(blank=True, limit_choices_to={'product_type': 'part'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_mo1', to='inventory.product', verbose_name='МО слот 1')),
                ('mo2', models.ForeignKey(blank=True, limit_choices_to={'product_type': 'part'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_mo2', to='inventory.product', verbose_name='МО слот 2')),
                ('mo3', models.ForeignKey(blank=True, limit_choices_to={'product_type': 'part'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_mo3', to='inventory.product', verbose_name='МО слот 3')),
                ('mo4', models.ForeignKey(blank=True, limit_choices_to={'product_type': 'part'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_mo4', to='inventory.product', verbose_name='МО слот 4')),
            ],
            options={
                'verbose_name': 'Артикул',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ('article',),
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Количество')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.bom', verbose_name='Спецификация')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='inventory.product', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Строка спецификации',
                'verbose_name_plural': 'Строки спецификации',
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product', verbose_name='Продукт'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='inventory_p_product_3c97c6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='inventory_p_is_acti_47a270_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('product', 'version')},
        ),
    ]
