# Generated by Django 5.2.7 on 2026-09-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mo5',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'part'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_mo5', to='inventory.product', verbose_name='МО слот 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='mo6',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'part'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_mo6', to='inventory.product', verbose_name='МО слот 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='mo7',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'part'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_mo7', to='inventory.product', verbose_name='МО слот 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='mo8',
            field=models.ForeignKey(blank=True, limit_choices_to={'product_type': 'part'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_mo8', to='inventory.product', verbose_name='МО слот 8'),
        ),
    ]
