# Generated by Django 5.2.7 on 2026-09-24 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_mo5_product_mo6_product_mo7_product_mo8'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alias_of',
            field=models.ForeignKey(blank=True, help_text='Если этот артикул — старый/дублирующий, укажите главный. Иначе пусто.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='inventory.product', verbose_name='Главный артикул'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['alias_of'], name='inventory_p_alias_o_ae832c_idx'),
        ),
    ]
