# Generated by Django 5.2.7 on 2026-09-14 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('user_repr', models.CharField(blank=True, default='', help_text='Снимок, чтобы не терять имя при удалении пользователя', max_length=150, verbose_name='Кто (имя)')),
                ('action', models.CharField(choices=[('create', 'Создано'), ('update', 'Изменено'), ('delete', 'Удалено')], db_index=True, max_length=16, verbose_name='Действие')),
                ('model_name', models.CharField(db_index=True, max_length=64, verbose_name='Модель')),
                ('object_id', models.BigIntegerField(db_index=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Объект')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Что изменилось')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='Снимок полей')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал изменений',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
