# Generated by Django 5.2.7 on 2026-09-11 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='Номер заказа')),
                ('kind', models.CharField(choices=[('production', 'Производственный'), ('shipment', 'На отгрузку')], default='production', max_length=16, verbose_name='Тип заказа')),
                ('customer', models.CharField(blank=True, default='', max_length=255, verbose_name='Заказчик')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('ready', 'Готов'), ('shipped', 'Отгружен'), ('closed', 'Закрыт')], default='new', max_length=16, verbose_name='Статус')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Подтягивается из карточки артикула, можно переопределить', max_length=255, verbose_name='Наименование')),
                ('quantity_planned', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='План, шт')),
                ('quantity_done', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Изготовлено, шт')),
                ('quantity_shipped', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Отгружено, шт')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('casting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_lines_casting', to='inventory.product', verbose_name='Артикул литья')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='inventory.product', verbose_name='Артикул (деталь после МО)')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('ready', 'Готов'), ('shipped', 'Отгружен'), ('closed', 'Закрыт')], max_length=16, verbose_name='Из')),
                ('status_to', models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('ready', 'Готов'), ('shipped', 'Отгружен'), ('closed', 'Закрыт')], max_length=16, verbose_name='В')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ('-changed_at',),
            },
        ),
    ]
