# Generated by Django 5.2.7 on 2026-09-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='machine',
            field=models.CharField(blank=True, default='', help_text='Например «6--5», «3--4». Свободный текст.', max_length=32, verbose_name='№ станка'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='places',
            field=models.IntegerField(blank=True, help_text='Количество грузовых мест', null=True, verbose_name='Мест'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='ready_date',
            field=models.DateField(blank=True, help_text='Когда планируется/состоялась готовность', null=True, verbose_name='Дата готовности'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='reserve_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Отклонение от плана: +6 → готовых 106; −1 → готовых 99', max_digits=14, verbose_name='Задел (дельта)'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='sequence',
            field=models.IntegerField(default=0, help_text='Порядковый номер строки внутри заказа', verbose_name='№ п/п в заказе'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='shipped_date',
            field=models.DateField(blank=True, help_text='Когда планируется/состоялась отгрузка', null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='weight_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Если пусто — считается из веса единицы × количество', max_digits=14, null=True, verbose_name='Вес партии, г'),
        ),
    ]
